# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-12 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
                ('card_id', models.CharField(max_length=32, unique=True)),
                ('male', models.BooleanField()),
                ('telephone', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=256)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Education')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Departments')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Employees')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salesmen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Employees')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Employees')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Subjects')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
