# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-13 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0002_employees_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128)),
                ('datetime', models.DateTimeField()),
                ('star_teacher', models.ManyToManyField(to='teach.Teachers')),
            ],
        ),
    ]
