# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-12 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('success', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=1)),
                ('discount', models.FloatField(default=1.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('real_pay', models.FloatField()),
                ('datetime', models.DateTimeField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.Grades')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
                ('tel', models.CharField(max_length=32)),
                ('access_time', models.DateTimeField()),
                ('status', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('test_time', models.DateTimeField()),
                ('score', models.FloatField(default=0)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.Grades')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.Parents')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='scores',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.Students'),
        ),
        migrations.AddField(
            model_name='orders',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.Students'),
        ),
        migrations.AddField(
            model_name='grades',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.Seasons'),
        ),
        migrations.AddField(
            model_name='grades',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Subjects'),
        ),
        migrations.AddField(
            model_name='grades',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Teachers'),
        ),
        migrations.AddField(
            model_name='auditions',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.Students'),
        ),
        migrations.AddField(
            model_name='auditions',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Teachers'),
        ),
    ]
